Update sync-from-repo1.yaml

diff --git a/.github/workflows/sync-from-repo1.yaml b/.github/workflows/sync-from-repo1.yaml
--- a/.github/workflows/sync-from-repo1.yaml
+++ b/.github/workflows/sync-from-repo1.yaml
@@ -62,7 +62,9 @@ jobs:
           mkdir -p source
           CHANGED_FILES="${{ steps.get-changes.outputs.changed_files }}"
           while IFS= read -r file; do
-            cp "temp_repo1/$file" source/
+            rel_file="${file#updates/}"
+            mkdir -p "source/$(dirname "$rel_file")"
+            cp "temp_repo1/$file" "source/$rel_file"
           done <<< "$CHANGED_FILES"
 
       - name: Remove deleted files from source folder in phrase-adoc-vt
@@ -70,8 +72,8 @@ jobs:
         run: |
           DELETED_FILES="${{ steps.get-changes.outputs.deleted_files }}"
           while IFS= read -r file; do
-            BASE_FILE=$(basename "$file")
-            rm -f "source/$BASE_FILE" || echo "File source/$BASE_FILE not found; skipping removal."
+            rel_file="${file#updates/}"
+            rm -f "source/$rel_file" || echo "File source/$rel_file not found; skipping removal."
           done <<< "$DELETED_FILES"
 
       - name: Update last synced commit and commit changes to phrase-adoc-vt
